# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
future: true
plugins: [jekyll-paginate]

# Setup
title:               Windvoice
tagline:             "A Coder\'s confession"
description:         ''
url:                 http://arieszhang.me
baseurl:             ''
paginate:            10

# About/contact
author:
  name:              Aries Zhang
  url:               https://github.com/aries-zhang
  email:             test@gmail.com

# Custom vars
version:             1.0.0
