# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
future: true
plugins: [jekyll-paginate]

# Setup
title:               Windvoice
tagline:             "Where the spirit of geek glints"
description:         "This is where the thoughts and life of a Coder, jogger and a football fan is recorded."
url:                 http://arieszhang.me
baseurl:             ''
paginate:            10

# About/contact
author:
  name:              Aries Zhang
  url:               https://github.com/aries-zhang
  email:             test@gmail.com

# Custom vars
version:             1.1.0
